### ISSUE TITLE
// used in URL's  between back-ticks are interpreted as comment

### ISSUE THREAD

**Issue by PitWenkin** [leejo/javascript-packer-perl#11]
When using back-ticks to define [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), `//` are interpreted as comments.

Un-minified code:
```
const foo = 'bar';
const hello = `https://www.world.com/${foo}`;
alert(hello);
```

Minified code:
```
const foo='bar';const hello=`https:alert(hello);
```

Expected minified code:
```
const foo='bar';const hello=`https://www.world.com/${foo}`;alert(hello);
```

**Comment by leejo** [comment]
v2.09 on its way to CPAN

**Comment by PitWenkin** [comment]
Unfortunately the bug still exists in v2.09

**Comment by leejo** [comment]
@PitWenkin - can you double and check and provide a test case? I added your example above as an explicit test case in the change: https://github.com/leejo/javascript-packer-perl/commit/ccb6268dca1b0d3e90ad9daabfbee5b0d0ed135c#diff-a73765d685709bb835b7b0fbfac475384ef6124d0767673d3053fa43b2ea8155

**Comment by PitWenkin** [comment]
After rebooting it worked 🤭 … sorry
