### ISSUE TITLE
Some spaces between back-ticks are removed

### ISSUE THREAD

**Issue by PitWenkin** [leejo/javascript-packer-perl#12]
When using back-ticks to define [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), no spaces should be stripped.

1. Leading and trailing spaces as well as spaces around `=` (maybe other signs too)  are however removed.

Un-minified code:
```
const string = ` This should be interpreted as normal string, and no space should be removed. Even if there is an = sign. `;
alert(string);
```

Minified code:
```
const string=`This should be interpreted as normal string,and no space should be removed.Even if there is an=sign.`;alert(string);
```

Expected minified code:
```
const string=` This should be interpreted as normal string, and no space should be removed. Even if there is an = sign. `;alert(string);
```

2. When using variables, spaces after variables are removed while space before them are left

Un-minified code:
```
const word = 'This';
const string =  ` ${word} should be interpreted as normal string, and no space should be removed. Even if there is an = sign. `;
alert(string);
```

Minified code:
```
const word='This';const string=` ${word}should be interpreted as normal string,and no space should be removed.Even if there is an=sign.`;alert(string);
```

Expected minified code:
```
const word='This';const string=` ${word} should be interpreted as normal string,and no space should be removed.Even if there is an = sign. `;alert(string);
```

**Comment by leejo** [comment]
I'll see if i can do something about this, but i am increasingly becoming more and more frustrated with way this distribution [works](https://github.com/leejo/javascript-packer-perl/commit/ccb6268dca1b0d3e90ad9daabfbee5b0d0ed135c) so am considering chucking it back into ADOPTME on CPAN. Will have an update sometime in the next couple of weeks.

**Comment by leejo** [comment]
v2.10 on its way to CPAN
