### ISSUE TITLE
Shrink Bug with $ variable

### ISSUE THREAD

**Issue by robertalvin** [leejo/javascript-packer-perl#4]
When using the 'shrink' compress option the following statement "var source = item.$source" is changed to  'var d=a.$d'. The '$source' is not the same  as 'source'.

**Comment by leejo** [comment]
Can you replicate this in a test case for me? Will make fixing a bit easier. Thanks!

**Comment by robertalvin** [comment]
Let me know if you need more than this.

Bob

Original JavaScript File:
//---------------------------------------------------------------------------------------------------------
// Source is not the same
//---------------------------------------------------------------------------------------------------------
function filteredData ()
{
    var data = [];

    $$("pivot").$$("data").data.each(function(item){
        //item is a visible item
        var source = item.$source;
        if(source){
            var raw = [].concat(source).map(id => $$("pivot").data.getItem(id));
            data = data.concat(raw);
        }
    });
    return data;
};

After minify with ‘shrink’ compression:
function filteredData(){var d=[]; $$("pivot").$$("data").data.each(function(a){var c=a.$c;if(c){var b=[].concat(c).map(id=> $$("pivot").data.getItem(id));d=d.concat(b)}});

**Comment by leejo** [comment]
What is the suffix `.$source` doing here on the `item` variable/object? That's not any javascript/jquery syntax i'm familiar with, neither a method call, associative array, or anything else I can recall.

**Comment by robertalvin** [comment]
That is the name of the variable in the object. A ‘$’ character is allowed in a variable name. In the Stackoverflow and Google search below you will see different case usages, but it looks like it originated with jQuery.

https://stackoverflow.com/questions/6288649/confusion-over-simple-variable-declaration-jquery-variable-vs-javascript-var
You seem to be confused about JavaScript variables. There is no such thing as "jQuery variables" and "non-jQuery variables". Some specific cases:
·         A variable declared with var is different to a variable without. "var x" is a local variable, so it will not share a value with other functions which also have a variable called "x". This is almost always a good thing, so you should almost always declare variables with "var".
·         The $ in jQuery is sort of special. It isn't that special; it's just that jQuery has declared a variable called "$" which does some fancy operations.
·         There is nothing special about variables that begin with "$". In other words, "$x" is just a variable name. It is a different variable to "x", and it isn't a "jQuery variable". It's just a JavaScript variable called "$x". (This is different from PHP, where the $ is actually a special variable syntax.)

https://www.google.com/search?rlz=1C1CHFX_enUS662US662&q=javascript+variable+with+%24&oq=javascript+variable+with+%24&gs_l=psy-ab.3..0j0i22i30k1l9.311127.316173.0.316446.26.26.0.0.0.0.162.2415.13j11.24.0....0...1.1.64.psy-ab..2.24.2410...35i39k1j0i67k1j0i131k1j0i20i263i264k1j0i20i264k1.0.M1NP5iiMAdA

**Comment by leejo** [comment]
OK, i suspected as much. I've added a test case and will look at when i get some time. Not sure when though and if this will be an easy fix as this module is a mass of regular expressions parsing javascript.

**Comment by robertalvin** [comment]
No rush on my account. I just renamed the ‘var source’ to ‘var src’ ;-)

**Comment by leejo** [comment]
Closing due to "can't be bothered to fix this myself"
