### ISSUE TITLE
JavaScript::Packer breaks code that relies on ASI

### ISSUE THREAD

**Issue by versable** [leejo/javascript-packer-perl#5]
After using JavaScript::Packer on a large project, we noticed that our Javascript code was broken in several instances. After inspecting the output, we noticed that JavaScript::Packer does not honor/check for code that relies on ASI [1].

This should at least be noted in the Documentation.

[1] https://tc39.github.io/ecma262/#sec-rules-of-automatic-semicolon-insertion

**Comment by versable** [comment]
Digging through the commits I have found the commit 664f836, which seems to remove the feature. Based on the (removed) comments there, I wouldn't call an ECMAScript specification 'invalid Javascript'.

**Comment by leejo** [comment]
> Digging through the commits I have found the commit 664f836, which seems to remove the feature. Based on the (removed) comments there, I wouldn't call an ECMAScript specification 'invalid Javascript'.

Hi, this change pre-dates my maintenance involvement. I will look at reverting that commit to see what impact it has, otherwise the usual "patches welcome" applies.

**Comment by leejo** [comment]
@versable - i've pushed the above commit to gh/5_asi_fix that reverts the aforementioned commit and fixes the conflicts. However tests fail. You're welcome to look into fixing them, I will not be.

**Comment by leejo** [comment]
@versable - for now I've made the suggested documentation changes, I'll push out the update to the module next week so you have chance to look at fixing the above tests if you're interested in doing so. Ta!

**Comment by versable** [comment]
@leejo first off, thanks for your fast reply, I (we) really appreciate it. I took a stab at this myself, from what I gathered, the old implementation failed for most ASL tests I wrote. I'd say that the ASL specs, while easy and solidly defined, cannot be solved with regex alone (Chomsky hierarchy comes to mind [1]), but I might be wrong.

I'd love to take a stab at this, as it is a nice exercise, but I am quite busy and I am sure that you are too.

Thanks for the swift response and the consequent updates.

[1] https://en.wikipedia.org/wiki/Chomsky_hierarchy

**Comment by leejo** [comment]
@versable - no problem. I'm not a fan of the implementation in these modules, namely using regex to parse js, CSS, etc; but they're "good enough" in most cases so...

**Comment by leejo** [comment]
@versable - v2.04 uploaded to CPAN - just a documentation change in this case.

**Comment by leejo** [comment]
Closing, the documentation change will suffice.
