### ISSUE TITLE
Incorrect regex when "best" compression matches ord check equal to 57

### ISSUE THREAD

**Issue by r3hp1c** [leejo/javascript-packer-perl#6]
While using Javascript::Packer on a large project that substitutes data into JavaScript I found that in some cases we were getting the "Invalid or unexpected token" error message for the minified JavaScript in the browser.

After investigation I found that the regular expression generated for the browser to un-minify was

`e=function(){return'([wyEHKLQW-Z]|0-9[0-9a-zA-Z])'}`

this caused that not all place holders were correctly replaced back due to this section **]|0-9[**

Expect that the regular expression should be

`e=function(){return'([wyEHKLQW-Z]|[0-9][0-9a-zA-Z])'}`

**Comment by leejo** [comment]
Do you have a test case for this? Would be helpful.

**Comment by r3hp1c** [comment]
Please see the pull request.  Added a test case before fixing the issue.

**Comment by leejo** [comment]
A ha! I shall close this in favour of #7
