### ISSUE TITLE
Option to keep sourceMappingURL

### ISSUE THREAD

**Issue by PitWenkin** [leejo/javascript-packer-perl#9]
I have added a [source map](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) to a compiled  javascript file, but after running it throught that packer the source map is gone.
I tried to play around with with the different compression options and the remove_copyright but no combination seems to leave code like `//# sourceMappingURL=http://example.com/path/to/your/sourcemap.map` in the result.

**Comment by leejo** [comment]
Hi @PitWenkin - can you provide an example snippet that shows the problem (a failing test case would be ideal).

**Comment by PitWenkin** [comment]
Hi the following would be the simplest code that does not work:
```
use JavaScript::Packer;
my $packer = JavaScript::Packer->init();
my $js = "//# sourceMappingURL=script.js.map
var one = 1;";
my $min_js = $packer->minify(\$js);
```

I expect `$min_js` to be:
```
//# sourceMappingURL=script.js.map
var one=1;
```

but it is:
```
var one=1;
```

**Comment by leejo** [comment]
OK, thanks. I'll try to get this fixed in the next week or three.

**Comment by PitWenkin** [comment]
It would be nice if the `remove_copyright` would still work …

**Comment by leejo** [comment]
OK! I believe this is fixed with v2.07, which is on its way to CPAN. Thanks!

**Comment by PitWenkin** [comment]
Hi,

unfortunately instead of a newline-character between the sourcemap an the code there is `__NEW_LINE__`.

Instead of:

```
//# sourceMappingURL=script.js.map
var one=1;
```

I get:

```
//# sourceMappingURL=script.js.map__NEW_LINE__var one=1;
```

It seems like https://github.com/leejo/javascript-packer-perl/blob/6c17564b71bc66fef644b0f860334f84bb2482dd/lib/JavaScript/Packer.pm#L625 does not match and therefor does not replace the placeholder.

**Comment by PitWenkin** [comment]
Some of my files are propperly minified, but not all.
I believe that it breaks if there is no comment between the sourcemap an the fist line of actual code …

**Comment by leejo** [comment]
Can you provide some extracts from the files so I can add these as test cases and fix this properly?

**Comment by PitWenkin** [comment]
Sorry for the delay, here are some examples were `__NEW_LINE__` is not replaced with a linebreak. I had to rename .js to .txt else the upload would not have worked

By adding a sourcemap to the first line of version 1.12 of jquery-ui [jquery-ui.txt](https://github.com/leejo/javascript-packer-perl/files/7538786/jquery-ui.txt)

> The file has comments between sourcemap and code, but code begins with `(`


This file: [collaboration-all.txt](https://github.com/leejo/javascript-packer-perl/files/7538779/collaboration-all.txt)

> The file does not have comments between sourcemap and code


This file [withoutcomment.txt](https://github.com/leejo/javascript-packer-perl/files/7538774/withoutcomment.txt)

> The file does not have comments between sourcemap and code


These files do work:
[withcomment.txt](https://github.com/leejo/javascript-packer-perl/files/7538772/withcomment.txt)
[withcomments.txt](https://github.com/leejo/javascript-packer-perl/files/7538773/withcomments.txt)

> Same code as the file above but with comments

**Comment by leejo** [comment]
OK, thanks! I'll try to have a look at this before the end of the week.

**Comment by leejo** [comment]
(I mean, feel free to have a go at a PR as well)

**Comment by leejo** [comment]
@PitWenkin - v2.08 on its way to CPAN, can you give that a go?

**Comment by PitWenkin** [comment]
> @PitWenkin - v2.08 on its way to CPAN, can you give that a go?

@leejo as far as I can tell all my files are now correct 👍
